In [1]:
import pandas as pd
business=pd.read_csv('C:\\Users\\m.maraqa\\Desktop\\MMA courses\\Fall 2022\\Data Mining and Visualization\\Group Project\\Yelp CSV\\yelp_business.csv')
reviews=pd.read_csv('C:\\Users\\m.maraqa\\Desktop\\MMA courses\\Fall 2022\\Data Mining and Visualization\\Group Project\\Yelp CSV\\yelp_review.csv')
user=pd.read_csv('C:\\Users\\m.maraqa\\Desktop\\MMA courses\\Fall 2022\\Data Mining and Visualization\\Group Project\\Yelp CSV\\yelp_user.csv')

We want to create a recommendation system based on the activity of friends. We will build an algorithm that analyzes the reviews of some users and flags their polarities. If polarity is positive, the friends of these users get ads on these places.


**Idea if we have time: associate reviews with business ids and categories. When a friend searches that category, he/she will get recommended the business the user reviewed positively**


We have decided to review all businesses, so we will be looking at the reviews, user and business tables


***Data Gathering***

    Step1: Create dataframe of users with at least one friend

    Step2: Merge reviews and ufrds table

***Preprocessing***

    Step1: Remove english stop words
    
    Step2: Remove punc
    
    Step3: Lowercase
    
    Step4: Remove extra stop words nltk missed (maybe)

***Data Analysis***

    Step1: Lemmatize/tokenize
    
    Step2: Get polarity
    
***Implementation***

Print message: "Some of your friends liked this"

If review positive, recommend to friend. Extra: only if friend looked for business category, recommend business to friend.

In [80]:
business

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
0,FYWN1wneV18bWNgQjJ2GNg,"""Dental by Design""",NaN,"""4855 E Warner Rd, Ste B9""",Ahwatukee,AZ,85044,33.330690,-111.978599,4.0,22,1,Dentists;General Dentistry;Health & Medical;Or...
1,He-G7vWjzVUysIKrfNbPUQ,"""Stephen Szabo Salon""",NaN,"""3101 Washington Rd""",McMurray,PA,15317,40.291685,-80.104900,3.0,11,1,Hair Stylists;Hair Salons;Men's Hair Salons;Bl...
2,KQPW8lFf1y5BT2MxiSZ3QA,"""Western Motor Vehicle""",NaN,"""6025 N 27th Ave, Ste 1""",Phoenix,AZ,85017,33.524903,-112.115310,1.5,18,1,Departments of Motor Vehicles;Public Services ...
3,8DShNS-LuFqpEWIp0HxijA,"""Sports Authority""",NaN,"""5000 Arizona Mills Cr, Ste 435""",Tempe,AZ,85282,33.383147,-111.964725,3.0,9,0,Sporting Goods;Shopping
4,PfOCPjBrlQAnz__NXj9h_w,"""Brick House Tavern + Tap""",NaN,"""581 Howe Ave""",Cuyahoga Falls,OH,44221,41.119535,-81.475690,3.5,116,1,American (New);Nightlife;Bars;Sandwiches;Ameri...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
174562,ALV5R8NkZ1KGOZeuZl3u0A,"""Whitby Toyota""",NaN,"""1025 Dundas Street W""",Whitby,ON,L1P 1Z1,43.873460,-78.968033,4.0,4,1,Car Dealers;Automotive
174563,gRGalHVu6BcaUDIAGVW_xQ,"""Village Auto Body""",NaN,"""3957 Brecksville Rd""",Richfield,OH,44286,41.243385,-81.636212,5.0,3,1,Body Shops;Automotive
174564,XXvZBIHoJBU5d6-a-oyMWQ,"""AAM""",NaN,"""1600 W Broadway Rd, Ste 200""",Tempe,AZ,85282,33.407914,-111.965098,1.5,19,1,Home Services;Property Management;Real Estate
174565,lNpPGgM96nPIYM1shxciHg,"""Bronze Beauty Spray Tanning""",NaN,"""300 Camp Horne Rd, Ste 250""",Pittsburgh,PA,15202,40.517724,-80.091466,5.0,14,1,Spray Tanning;Tanning;Beauty & Spas
174566,viKaP26BcHU6cLx8sf4gKg,"""Phoenix Pharmacy""",NaN,"""1701 East Thomas Rd, Ste 105""",Phoenix,AZ,85016,33.479861,-112.044689,5.0,4,1,Drugstores;Shopping;Health & Medical

In [98]:
user.shape

(1326100, 22)

In [7]:
# data gath step 1
ufrds=user[user.friends != 'None']

In [4]:
ufrds

,user_id,name,review_count,yelping_since,friends,useful,funny,cool,fans,elite,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,JJ-aSuM4pCFPdkfoZ34q0Q,Chris,10,2013-09-24,"0njfJmB-7n84DlIgUByCNw, rFn3Xe3RqHxRSxWOU19Gpg...",0,0,0,0,None,...,0,0,0,0,0,0,0,0,0,0
17,h5ERTYn2vQ1QbjTZvfWPaA,Bobby,3,2017-01-07,"jYiZnueCr7gVq9T34xoa7g, yFLXGdY6rpHt7hRiwEFMag...",0,0,0,0,None,...,0,0,0,0,0,0,0,0,0,0
18,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,0,0,0,0,1,1,1,1,2,0
44,fV8Yr0c5tFQTQ2SRRJHXHw,Michelle,50,2007-08-22,"HDb4fBWIAQ-foS8qLJty9w, x0hBZsmBTYxhjjx0MShz1A...",43,12,5,1,2009,...,4,0,0,0,9,7,7,7,4,0
74,aw973Pm1nrTbRjP4zY9B9g,Kenny,762,2008-09-23,"Cit5yho-DqotA0BnXHErTQ, bm2DqfP4P454FjEtCbZdkQ...",174,151,67,27,"2014, 2016, 2013, 2015, 2010, 2012, 2011",...,4,2,7,0,16,52,47,47,14,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1320276,_IAjRAnrgDk9ymGoE0Ri0A,Megan,7,2016-01-26,Ip-IoagS2AsWmIChHw03ug,0,0,0,0,None,...,0,0,0,0,0,0,0,0,0,0
1320277,ZDd4asPfshXeYZQCmR1ydg,Angelique,9,2014-02-14,ZJQY-xXXRMTOuIqC85DBGA,1,0,0,0,None,...,1,0,0,0,1,1,0,0,0,0
1320278,_DpQ25-kJ2RBQ6yplqSwcQ,Alex,3,2014-09-11,_5VyC9QOdtManMMLUeSusQ,0,0,0,0,None,...,0,0,0,0,0,0,0,0,0,0
1320279,78A8jO31AT51Fsa0k4PbJw,Scott,2,2011-01-24,AsTB1AeXucIESN9ZrqDWbQ,0,0,0,0,None,...,0,0,0,0,0,0,0,0,0,0
1320280,XMb9B3zgG1Uxc69-ibynXg,Marina,1,2014-01-13,9W73B44Iw8WslrTNB2CdCg,0,0,0,0,None,...,0,0,0,0,0,0,0,0,0,0

In [3]:
reviews

,review_id,user_id,business_id,stars,date,text,useful,funny,cool
0,vkVSCC7xljjrAI4UGfnKEQ,bv2nCi5Qv5vroFiqKGopiw,AEx2SYEUJmTxVVB18LlCwA,5,2016-05-28,Super simple place but amazing nonetheless. It...,0,0,0
1,n6QzIUObkYshz4dz2QRJTw,bv2nCi5Qv5vroFiqKGopiw,VR6GpWIda3SfvPC-lg9H3w,5,2016-05-28,Small unassuming place that changes their menu...,0,0,0
2,MV3CcKScW05u5LVfF6ok0g,bv2nCi5Qv5vroFiqKGopiw,CKC0-MOWMqoeWf6s-szl8g,5,2016-05-28,Lester's is located in a beautiful neighborhoo...,0,0,0
3,IXvOzsEMYtiJI0CARmj77Q,bv2nCi5Qv5vroFiqKGopiw,ACFtxLv8pGrrxMm6EgjreA,4,2016-05-28,Love coming here. Yes the place always needs t...,0,0,0
4,L_9BTb55X0GDtThi6GlZ6w,bv2nCi5Qv5vroFiqKGopiw,s2I_Ni76bjJNK9yG60iD-Q,4,2016-05-28,Had their chocolate almond croissant and it wa...,0,0,0
...,...,...,...,...,...,...,...,...,...
5261663,PoGSiNz1X5SUu0qEt-qM5w,mPjPyipaD0C_myqWqDipZg,Ngk84Ax1tXgpoJFEGxot3w,1,2011-11-21,"Bought groupon $39 for 4 months from groupon, ...",36,3,3
5261664,-CJNPrDWgIkorx4iEZJXIg,mPjPyipaD0C_myqWqDipZg,pOEL97ld-FJMKO8Ki8JmYg,3,2016-04-30,"Spring rolls was pretty good, cod was a bit ra...",0,0,0
5261665,W9eVvOcpBvG6lpJPoJOxuA,mPjPyipaD0C_myqWqDipZg,5ubokMNw8qfbX2WtxgJG1Q,4,2011-10-23,"Had a 8 dish set meal, was enough for 10 peopl...",3,0,1
5261666,hqQ1UTFKMN2P1ezUow48OQ,mPjPyipaD0C_myqWqDipZg,EO3i5kTUG7_S2OIQ23sdSA,3,2011-11-07,"A small, cozy family run Authentic korean rest...",2,0,0
5261667,ldsIs3sGXPJ7WM7VyAm4lQ,mPjPyipaD0C_myqWqDipZg,HloEEXm_QzEpycuwA_RtQA,3,2011-11-15,Really nice atmosphere and settings and very c...,0,1,1

In [8]:
# data gath step 2
urev=pd.merge(ufrds, reviews, how = 'inner', on = 'user_id')

In [14]:
urev

,user_id,name,review_count,yelping_since,friends,useful_x,funny_x,cool_x,fans,elite,...,compliment_writer,compliment_photos,review_id,business_id,stars,date,text,useful_y,funny_y,cool_y
0,JJ-aSuM4pCFPdkfoZ34q0Q,Chris,10,2013-09-24,"0njfJmB-7n84DlIgUByCNw, rFn3Xe3RqHxRSxWOU19Gpg...",0,0,0,0,None,...,0,0,rCJcO4xS3kxjNTxpN8HPVA,Z5BHNFjt7ZmAse2kKlw2uA,3,2013-10-29,Was in town to watch the Seahawks vs Panthers ...,0,0,0
1,h5ERTYn2vQ1QbjTZvfWPaA,Bobby,3,2017-01-07,"jYiZnueCr7gVq9T34xoa7g, yFLXGdY6rpHt7hRiwEFMag...",0,0,0,0,None,...,0,0,vOj_x4SqxlwaCjBPyVSVrw,7FZ5yyfuOqBRlNAYHj2wqw,1,2017-06-24,"Ok let me start this, I was approved for a son...",2,0,0
2,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,2,0,1YMEs_zIkhRAWpYx4VTObQ,ehMxdQ9FfF4uOcGPKNWNOg,4,2017-03-01,Cafe Rio is a close match to an Authentic Mexi...,0,0,0
3,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,2,0,_Z5fZjlDWsALbDfB0viRCg,p6p9C015fOq8jxxBNGDl1g,5,2012-12-20,Grayson knew exactly what I had in mind for my...,2,0,0
4,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,2,0,cnImzPutyftEAznYYrXViQ,ZDdEtIFhLsoydDvB8joYrA,1,2010-07-11,Place isn't and won't ever have the same taste...,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3927716,_DpQ25-kJ2RBQ6yplqSwcQ,Alex,3,2014-09-11,_5VyC9QOdtManMMLUeSusQ,0,0,0,0,None,...,0,0,xM7eW34q42gJoiRjNjtgWw,YTMbzy3SXiDtqQOfZRD7lw,5,2016-09-26,The best place where you'll find great service...,0,0,0
3927717,_DpQ25-kJ2RBQ6yplqSwcQ,Alex,3,2014-09-11,_5VyC9QOdtManMMLUeSusQ,0,0,0,0,None,...,0,0,AfXGm9srusEF8PCwZ7nM9g,tSf-o4rtIZqb7S3jytzm5A,5,2014-09-11,This is the only garage company who I'll be ca...,0,0,0
3927718,78A8jO31AT51Fsa0k4PbJw,Scott,2,2011-01-24,AsTB1AeXucIESN9ZrqDWbQ,0,0,0,0,None,...,0,0,stw08_9Aj9Sd4UYlWRKqlw,0qsarzXaZau8REdE0rToxA,5,2011-01-24,Absolutely the best I have tasted in the Cleve...,0,0,0
3927719,78A8jO31AT51Fsa0k4PbJw,Scott,2,2011-01-24,AsTB1AeXucIESN9ZrqDWbQ,0,0,0,0,None,...,0,0,LCpwMHT9LjWfwukqxZ3hng,dQwjYLmQXb06CpMPIpm5-g,5,2011-01-25,One of my favorite places to eat. The best Mex...,0,0,1
3927720,XMb9B3zgG1Uxc69-ibynXg,Marina,1,2014-01-13,9W73B44Iw8WslrTNB2CdCg,0,0,0,0,None,...,0,0,G3Ckqy9_7T7008RVhv6A1A,IZKjHtCuRlbhyD1WtGd8uA,5,2014-10-13,This service is amazing. I got text messages a...,0,0,0

In [9]:
# Preproc step 1
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\m.maraqa\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [12]:
#Decreasing dataframe size to save processing time 
urev2=urev.iloc[0:1000,:]

In [13]:
urev2

,user_id,name,review_count,yelping_since,friends,useful_x,funny_x,cool_x,fans,elite,...,compliment_writer,compliment_photos,review_id,business_id,stars,date,text,useful_y,funny_y,cool_y
0,JJ-aSuM4pCFPdkfoZ34q0Q,Chris,10,2013-09-24,"0njfJmB-7n84DlIgUByCNw, rFn3Xe3RqHxRSxWOU19Gpg...",0,0,0,0,None,...,0,0,rCJcO4xS3kxjNTxpN8HPVA,Z5BHNFjt7ZmAse2kKlw2uA,3,2013-10-29,Was in town to watch the Seahawks vs Panthers ...,0,0,0
1,h5ERTYn2vQ1QbjTZvfWPaA,Bobby,3,2017-01-07,"jYiZnueCr7gVq9T34xoa7g, yFLXGdY6rpHt7hRiwEFMag...",0,0,0,0,None,...,0,0,vOj_x4SqxlwaCjBPyVSVrw,7FZ5yyfuOqBRlNAYHj2wqw,1,2017-06-24,"Ok let me start this, I was approved for a son...",2,0,0
2,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,2,0,1YMEs_zIkhRAWpYx4VTObQ,ehMxdQ9FfF4uOcGPKNWNOg,4,2017-03-01,Cafe Rio is a close match to an Authentic Mexi...,0,0,0
3,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,2,0,_Z5fZjlDWsALbDfB0viRCg,p6p9C015fOq8jxxBNGDl1g,5,2012-12-20,Grayson knew exactly what I had in mind for my...,2,0,0
4,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,2,0,cnImzPutyftEAznYYrXViQ,ZDdEtIFhLsoydDvB8joYrA,1,2010-07-11,Place isn't and won't ever have the same taste...,1,0,0

In [18]:
#remove stopwords
pat = r'\b(?:{})\b'.format('|'.join(stop))
urev2['review_without_stopwords'] = urev2['text'].str.replace(pat, '', regex = True)
urev2['review_without_stopwords'] = urev2['review_without_stopwords'].str.replace(r'\s+', ' ', regex = True)
#remove punc
urev2['no_punc'] = urev2['review_without_stopwords'].str.replace('[^\w\s]', '')
#lowercase
urev2['final_rev'] = urev2['no_punc'].str.lower()

<ipython-input-18-58769c4c0a39>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  urev2['review_without_stopwords'] = urev2['text'].str.replace(pat, '', regex = True)
<ipython-input-18-58769c4c0a39>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  urev2['review_without_stopwords'] = urev2['review_without_stopwords'].str.replace(r'\s+', ' ', regex = True)

In [41]:
nltk.download('punkt')
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\m.maraqa\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\m.maraqa\AppData\Roaming\nltk_data...

In [44]:
#Tokenize and lemmatize reviews
urev2['lem'] = ''
for i in range(len(urev2)):
    tokens_words = nltk.word_tokenize(urev2['final_rev'][i])
    urev2['lem'][i] = ' '.join([lemmatizer.lemmatize(w) for w in tokens_words])

<ipython-input-44-f43802632a8f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  urev2['lem'] = ''
<ipython-input-44-f43802632a8f>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  urev2['lem'][i] = ' '.join([lemmatizer.lemmatize(w) for w in tokens_words])
C:\Users\m.maraqa\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3437: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [50]:
!pip install textblob

Collecting textblob
  Downloading textblob-0.17.1-py2.py3-none-any.whl (636 kB)
Requirement already satisfied: nltk>=3.1 in c:\users\m.maraqa\anaconda3\lib\site-packages (from textblob) (3.6.1)
Requirement already satisfied: click in c:\users\m.maraqa\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (7.1.2)
Requirement already satisfied: tqdm in c:\users\m.maraqa\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (4.59.0)
Requirement already satisfied: joblib in c:\users\m.maraqa\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (1.0.1)
Requirement already satisfied: regex in c:\users\m.maraqa\anaconda3\lib\site-packages (from nltk>=3.1->textblob) (2021.4.4)
Installing collected packages: textblob
Successfully installed textblob-0.17.1

In [69]:
#get polarity
import textblob
from textblob import TextBlob

urev2['polarity'] = ''
for i in range(len(urev2)): 
    urev2['polarity'][i] = TextBlob(urev2['lem'][i]).sentiment.polarity

<ipython-input-69-f330dc30a561>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  urev2['polarity'] = ''
<ipython-input-69-f330dc30a561>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  urev2['polarity'][i] = TextBlob(urev2['lem'][i]).sentiment.polarity
C:\Users\m.maraqa\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3437: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [76]:
urev2

,user_id,name,review_count,yelping_since,friends,useful_x,funny_x,cool_x,fans,elite,...,date,text,useful_y,funny_y,cool_y,review_without_stopwords,no_punc,final_rev,lem,polarity
0,JJ-aSuM4pCFPdkfoZ34q0Q,Chris,10,2013-09-24,"0njfJmB-7n84DlIgUByCNw, rFn3Xe3RqHxRSxWOU19Gpg...",0,0,0,0,None,...,2013-10-29,Was in town to watch the Seahawks vs Panthers ...,0,0,0,Was town watch Seahawks vs Panthers September ...,Was town watch Seahawks vs Panthers September ...,was town watch seahawks vs panthers september ...,wa town watch seahawks v panther september fir...,0.329657
1,h5ERTYn2vQ1QbjTZvfWPaA,Bobby,3,2017-01-07,"jYiZnueCr7gVq9T34xoa7g, yFLXGdY6rpHt7hRiwEFMag...",0,0,0,0,None,...,2017-06-24,"Ok let me start this, I was approved for a son...",2,0,0,"Ok let start , I approved sonic , told nope br...",Ok let start I approved sonic told nope brin...,ok let start i approved sonic told nope brin...,ok let start i approved sonic told nope bring ...,0.073006
2,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,2017-03-01,Cafe Rio is a close match to an Authentic Mexi...,0,0,0,Cafe Rio close match Authentic Mexican Restaur...,Cafe Rio close match Authentic Mexican Restaur...,cafe rio close match authentic mexican restaur...,cafe rio close match authentic mexican restaur...,0.195304
3,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,2012-12-20,Grayson knew exactly what I had in mind for my...,2,0,0,Grayson knew exactly I mind project plus gave ...,Grayson knew exactly I mind project plus gave ...,grayson knew exactly i mind project plus gave ...,grayson knew exactly i mind project plus gave ...,0.55
4,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,2010-07-11,Place isn't and won't ever have the same taste...,1,0,0,Place ' ' ever taste since switched owners.,Place ever taste since switched owners,place ever taste since switched owners,place ever taste since switched owner,0.0

In [91]:
urev2=pd.merge(urev2, business, how = 'inner', on = 'business_id')

In [82]:
urev2

,user_id,name_x,review_count_x,yelping_since,friends,useful_x,funny_x,cool_x,fans,elite,...,address,city,state,postal_code,latitude,longitude,stars_y,review_count_y,is_open,categories
0,JJ-aSuM4pCFPdkfoZ34q0Q,Chris,10,2013-09-24,"0njfJmB-7n84DlIgUByCNw, rFn3Xe3RqHxRSxWOU19Gpg...",0,0,0,0,None,...,"""800 S Mint St""",Charlotte,NC,28202,35.226047,-80.853078,4.0,104,1,Professional Sports Teams;Stadiums & Arenas;Ar...
1,h5ERTYn2vQ1QbjTZvfWPaA,Bobby,3,2017-01-07,"jYiZnueCr7gVq9T34xoa7g, yFLXGdY6rpHt7hRiwEFMag...",0,0,0,0,None,...,"""2121 North Arizona Ave""",Chandler,AZ,85225,33.338537,-111.840196,3.0,44,1,Car Dealers;Auto Repair;Automotive
2,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,"""15768 N Frank Lloyd Wright Blvd""",Scottsdale,AZ,85260,33.628887,-111.889024,3.5,97,1,Cafes;Mexican;Restaurants
3,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,"""8711 E Pinnacle Peak Rd, Ste 379""",Scottsdale,AZ,85255,33.699108,-111.893058,5.0,33,1,Home Services;Landscape Architects;Landscaping...
4,jYnkJR3T8yCERXywoVhWYA,Hugo,48,2010-07-06,"hkXekeW_Jj6mIy8r8N7r1Q, dQDpV-VUtwYGqHznuRV-yw...",15,6,2,3,None,...,"""3130 E Union Hills Dr""",Phoenix,AZ,85050,33.655629,-112.015465,3.5,6,0,Restaurants;Pizza

In [83]:
#this acts like web IP address identifier
frdID = input()

0njfJmB-7n84DlIgUByCNw

In [4]:
srch = input('Search Bar:')

KeyboardInterrupt: Interrupted by user

In [93]:
print(urev2.columns)

Index(['user_id', 'name_x', 'review_count_x', 'yelping_since', 'friends',
       'useful_x', 'funny_x', 'cool_x', 'fans', 'elite', 'average_stars',
       'compliment_hot', 'compliment_more', 'compliment_profile',
       'compliment_cute', 'compliment_list', 'compliment_note',
       'compliment_plain', 'compliment_cool', 'compliment_funny',
       'compliment_writer', 'compliment_photos', 'review_id', 'business_id',
       'stars_x', 'date', 'text', 'useful_y', 'funny_y', 'cool_y',
       'review_without_stopwords', 'no_punc', 'final_rev', 'lem', 'polarity',
       'name_y', 'neighborhood_x', 'address_x', 'city_x', 'state_x',
       'postal_code_x', 'latitude_x', 'longitude_x', 'stars_y',
       'review_count_y', 'is_open_x', 'categories_x', 'name', 'neighborhood_y',
       'address_y', 'city_y', 'state_y', 'postal_code_y', 'latitude_y',
       'longitude_y', 'stars', 'review_count', 'is_open_y', 'categories_y'],
      dtype='object')

In [95]:
for f in range(len(urev2)):
    if frdID in urev2['friends'][f]:
        if urev2['polarity'][f] > 0:
            words = srch.split(' ')
            for x in words:
                if x in urev2['categories_y'][f]:
                    print('Your friend likes this. You might too!\n', urev2['name_y'][f]'\n')
                    break
        else:
            print('no friend activity-based ad to show\n')
            break
    else:
        print('no friend activity-based ad to show\n')

We think you might like this.
 "Bank of America Stadium"
no friend activity-based ad to show
no friend activity-based ad to show
no friend activity-based ad to show
no friend activity-based ad to show