***Google Maps Distance Matrix***

In [ ]:
pip install -U googlemaps

In [7]:
import pandas as pd
import googlemaps
import requests 
from pprint import pprint

In [2]:
#reading API key 
f = open('C:\\Users\\m.maraqa\\Desktop\\MMA courses\\Fall 2022\\Decision Analytics\\Project\\Google Maps API Key.txt', 'r')
api_key = f.readline()
f.close()

In [3]:
maps = googlemaps.Client(api_key)

In [12]:
url = 'https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&' 
#adis = UofT, Loblaws MLG, NoFrills Joe's, Walmart, Grocery Gateway, Metro
origin = '27 King\'s College Cir, Toronto, ON M5S | 60 Carlton St., Toronto, ON M5B 1L1 | Rocco\'s NOFRILLS Toronto, 200 Front St E, Toronto, ON M5A 4T9| 345 Bloor St E Unit 1A Unit 1A, Toronto, ON M4W 3J6 | 225 Rexdale Blvd, Etobicoke, ON M9W 1P7 | Dufferin Mall Supercentre, 900 Dufferin St, Toronto, ON M6H 4A9 | Loblaws Queen Street, 585 Queen St W, Toronto, ON M5V 2B7 | 444 Yonge St, Toronto, ON M5G 2B3'
dest = '27 King\'s College Cir, Toronto, ON M5S | 60 Carlton St., Toronto, ON M5B 1L1 | Rocco\'s NOFRILLS Toronto, 200 Front St E, Toronto, ON M5A 4T9| 345 Bloor St E Unit 1A Unit 1A, Toronto, ON M4W 3J6 | 225 Rexdale Blvd, Etobicoke, ON M9W 1P7 | Dufferin Mall Supercentre, 900 Dufferin St, Toronto, ON M6H 4A9 | Loblaws Queen Street, 585 Queen St W, Toronto, ON M5V 2B7 | 444 Yonge St, Toronto, ON M5G 2B3'
mode = 'transit&transit_mode=subway'
#get response
response = requests.get(url+'origins='+origin+'&destinations='+dest+'&mode='+mode+'&key='+api_key) #defualt mode of transport is driving. Other modes will have to be passed in mode argument

In [13]:
pprint(response.json()['rows'])

[{'elements': [{'status': 'ZERO_RESULTS'},
               {'distance': {'text': '2.9 mi', 'value': 4684},
                'duration': {'text': '22 mins', 'value': 1325},
                'status': 'OK'},
               {'distance': {'text': '2.6 mi', 'value': 4187},
                'duration': {'text': '34 mins', 'value': 2012},
                'status': 'OK'},
               {'distance': {'text': '1.9 mi', 'value': 3106},
                'duration': {'text': '22 mins', 'value': 1294},
                'status': 'OK'},
               {'distance': {'text': '13.4 mi', 'value': 21637},
                'duration': {'text': '57 mins', 'value': 3397},
                'status': 'OK'},
               {'distance': {'text': '2.8 mi', 'value': 4457},
                'duration': {'text': '24 mins', 'value': 1431},
                'status': 'OK'},
               {'distance': {'text': '1.4 mi', 'value': 2314},
                'duration': {'text': '29 mins', 'value': 1721},
                'status': 'OK'},
               {'distance': {'text': '0.8 mi', 'value': 1236},
                'duration': {'text': '16 mins', 'value': 933},
                'status': 'OK'}]},
 {'elements': [{'distance': {'text': '2.9 mi', 'value': 4747},
                'duration': {'text': '24 mins', 'value': 1429},
                'status': 'OK'},
               {'status': 'ZERO_RESULTS'},
               {'distance': {'text': '2.2 mi', 'value': 3573},
                'duration': {'text': '28 mins', 'value': 1683},
                'status': 'OK'},
               {'distance': {'text': '1.2 mi', 'value': 2003},
                'duration': {'text': '15 mins', 'value': 878},
                'status': 'OK'},
               {'distance': {'text': '13.3 mi', 'value': 21368},
                'duration': {'text': '54 mins', 'value': 3243},
                'status': 'OK'},
               {'distance': {'text': '3.7 mi', 'value': 5991},
                'duration': {'text': '27 mins', 'value': 1596},
                'status': 'OK'},
               {'distance': {'text': '1.9 mi', 'value': 3055},
                'duration': {'text': '39 mins', 'value': 2344},
                'status': 'OK'},
               {'distance': {'text': '0.2 mi', 'value': 332},
                'duration': {'text': '4 mins', 'value': 261},
                'status': 'OK'}]},
 {'elements': [{'distance': {'text': '2.7 mi', 'value': 4319},
                'duration': {'text': '32 mins', 'value': 1938},
                'status': 'OK'},
               {'distance': {'text': '2.3 mi', 'value': 3641},
                'duration': {'text': '27 mins', 'value': 1595},
                'status': 'OK'},
               {'status': 'ZERO_RESULTS'},
               {'distance': {'text': '3.2 mi', 'value': 5092},
                'duration': {'text': '35 mins', 'value': 2082},
                'status': 'OK'},
               {'distance': {'text': '13.1 mi', 'value': 21004},
                'duration': {'text': '57 mins', 'value': 3422},
                'status': 'OK'},
               {'distance': {'text': '5.2 mi', 'value': 8342},
                'duration': {'text': '43 mins', 'value': 2589},
                'status': 'OK'},
               {'distance': {'text': '2.0 mi', 'value': 3247},
                'duration': {'text': '42 mins', 'value': 2539},
                'status': 'OK'},
               {'distance': {'text': '2.2 mi', 'value': 3529},
                'duration': {'text': '25 mins', 'value': 1521},
                'status': 'OK'}]},
 {'elements': [{'distance': {'text': '2.0 mi', 'value': 3161},
                'duration': {'text': '20 mins', 'value': 1226},
                'status': 'OK'},
               {'distance': {'text': '1.3 mi', 'value': 2149},
                'duration': {'text': '16 mins', 'value': 965},
                'status': 'OK'},
               {'distance': {'text': '3.1 mi', 'value': 5009},
                'duration': {'text': '34 mins', 'value': 2058},
                'status': 'OK'},
               {'status': 'ZERO_RESULTS'},
               {'distance': {'text': '12.3 mi', 'value': 19730},
                'duration': {'text': '56 mins', 'value': 3388},
                'status': 'OK'},
               {'distance': {'text': '3.5 mi', 'value': 5604},
                'duration': {'text': '19 mins', 'value': 1141},
                'status': 'OK'},
               {'distance': {'text': '3.7 mi', 'value': 5926},
                'duration': {'text': '43 mins', 'value': 2608},
                'status': 'OK'},
               {'distance': {'text': '1.3 mi', 'value': 2031},
                'duration': {'text': '15 mins', 'value': 873},
                'status': 'OK'}]},
 {'elements': [{'distance': {'text': '14.5 mi', 'value': 23256},
                'duration': {'text': '1 hour 17 mins', 'value': 4592},
                'status': 'OK'},
               {'distance': {'text': '15.4 mi', 'value': 24802},
                'duration': {'text': '1 hour 20 mins', 'value': 4824},
                'status': 'OK'},
               {'distance': {'text': '16.9 mi', 'value': 27242},
                'duration': {'text': '1 hour 38 mins', 'value': 5896},
                'status': 'OK'},
               {'distance': {'text': '15.0 mi', 'value': 24178},
                'duration': {'text': '1 hour 10 mins', 'value': 4206},
                'status': 'OK'},
               {'status': 'ZERO_RESULTS'},
               {'distance': {'text': '12.1 mi', 'value': 19405},
                'duration': {'text': '1 hour 1 min', 'value': 3683},
                'status': 'OK'},
               {'distance': {'text': '14.6 mi', 'value': 23476},
                'duration': {'text': '1 hour 30 mins', 'value': 5402},
                'status': 'OK'},
               {'distance': {'text': '15.3 mi', 'value': 24684},
                'duration': {'text': '1 hour 19 mins', 'value': 4732},
                'status': 'OK'}]},
 {'elements': [{'distance': {'text': '2.9 mi', 'value': 4683},
                'duration': {'text': '26 mins', 'value': 1557},
                'status': 'OK'},
               {'distance': {'text': '3.9 mi', 'value': 6229},
                'duration': {'text': '30 mins', 'value': 1799},
                'status': 'OK'},
               {'distance': {'text': '5.4 mi', 'value': 8669},
                'duration': {'text': '47 mins', 'value': 2801},
                'status': 'OK'},
               {'distance': {'text': '3.5 mi', 'value': 5605},
                'duration': {'text': '20 mins', 'value': 1171},
                'status': 'OK'},
               {'distance': {'text': '9.3 mi', 'value': 14958},
                'duration': {'text': '48 mins', 'value': 2895},
                'status': 'OK'},
               {'status': 'ZERO_RESULTS'},
               {'distance': {'text': '2.2 mi', 'value': 3605},
                'duration': {'text': '44 mins', 'value': 2656},
                'status': 'OK'},
               {'distance': {'text': '3.8 mi', 'value': 6111},
                'duration': {'text': '28 mins', 'value': 1707},
                'status': 'OK'}]},
 {'elements': [{'distance': {'text': '1.4 mi', 'value': 2314},
                'duration': {'text': '30 mins', 'value': 1796},
                'status': 'OK'},
               {'distance': {'text': '2.7 mi', 'value': 4359},
                'duration': {'text': '27 mins', 'value': 1611},
                'status': 'OK'},
               {'distance': {'text': '2.0 mi', 'value': 3272},
                'duration': {'text': '41 mins', 'value': 2484},
                'status': 'OK'},
               {'distance': {'text': '3.6 mi', 'value': 5811},
                'duration': {'text': '35 mins', 'value': 2098},
                'status': 'OK'},
               {'distance': {'text': '13.2 mi', 'value': 21311},
                'duration': {'text': '1 hour 1 min', 'value': 3664},
                'status': 'OK'},
               {'distance': {'text': '2.2 mi', 'value': 3605},
                'duration': {'text': '46 mins', 'value': 2740},
                'status': 'OK'},
               {'status': 'ZERO_RESULTS'},
               {'distance': {'text': '1.7 mi', 'value': 2774},
                'duration': {'text': '36 mins', 'value': 2147},
                'status': 'OK'}]},
 {'elements': [{'distance': {'text': '0.8 mi', 'value': 1236},
                'duration': {'text': '16 mins', 'value': 980},
                'status': 'OK'},
               {'distance': {'text': '0.2 mi', 'value': 332},
                'duration': {'text': '4 mins', 'value': 264},
                'status': 'OK'},
               {'distance': {'text': '1.7 mi', 'value': 2751},
                'duration': {'text': '25 mins', 'value': 1475},
                'status': 'OK'},
               {'distance': {'text': '1.2 mi', 'value': 1891},
                'duration': {'text': '13 mins', 'value': 808},
                'status': 'OK'},
               {'distance': {'text': '13.2 mi', 'value': 21250},
                'duration': {'text': '53 mins', 'value': 3156},
                'status': 'OK'},
               {'distance': {'text': '3.7 mi', 'value': 5879},
                'duration': {'text': '25 mins', 'value': 1516},
                'status': 'OK'},
               {'distance': {'text': '1.7 mi', 'value': 2775},
                'duration': {'text': '35 mins', 'value': 2125},
                'status': 'OK'},
               {'status': 'ZERO_RESULTS'}]}]

In [19]:
org_dest = pd.DataFrame()
places = ['UofT','Loblaws MLG', 'No Frills', 'No Frills Joe\'s','Walmart', 'Grocery Gateway', 'Loblaws', 'Metro']
p = len(places)

Os = []
Ds = []
meters = []
sec = []
for o in range(p):
    for d in range(p):
        Os.append(places[o]) 
        Ds.append(places[d])
        if response.json()['rows'][o]['elements'][d]['status'] == 'ZERO_RESULTS':
            meters.append(0)
            sec.append(0)
        else:
            meters.append(response.json()['rows'][o]['elements'][d]['distance']['value'])
            sec.append(response.json()['rows'][o]['elements'][d]['duration']['value'])

org_dest['Origin'] = Os
org_dest['Destination'] = Ds
org_dest['Travel Distance (m)'] = meters
org_dest['Travel Duration (s)'] = sec

#export to excel 
org_dest.to_csv(r'C:\\Users\\m.maraqa\\Desktop\\MMA courses\\Fall 2022\\Decision Analytics\\Project\\Origin Destination Matrix_'+mode+'.csv', index = False)

org_dest

   Origin      Destination  Travel Distance (m)  Travel Duration (s)
0    UofT             UofT                    0                    0
1    UofT      Loblaws MLG                 4684                 1325
2    UofT        No Frills                 4187                 2012
3    UofT  No Frills Joe's                 3106                 1294
4    UofT          Walmart                21637                 3397
..    ...              ...                  ...                  ...
59  Metro  No Frills Joe's                 1891                  808
60  Metro          Walmart                21250                 3156
61  Metro  Grocery Gateway                 5879                 1516
62  Metro          Loblaws                 2775                 2125
63  Metro            Metro                    0                    0

[64 rows x 4 columns]